#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

exec xsetroot -cursor_name left_ptr & # fix cursor
exec nitrogen --restore & # restore background
exec sct 3800 & # set yellow filter
exec picom & # run compositor
exec polybar --config=$HOME/.config/polybar/config # run polybar
